services:
  boston-db:
    container_name: boston-db
    env_file: .env
    image: "postgres:latest"
    ports:
      - "5432:5432"
    volumes:
      - boston-data:/var/lib/postgresql/data/

  boston-app:
    container_name: boston-app
    environment:
      DB_HOST: 172.17.0.2
    ports:
      - "8080:8080"
    image: "otreblan/app:v1.0"

volumes:
  boston-data:
    name: boston-data
    driver: local
